# Generated by Django 5.1.7 on 2025-03-13 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_alter_customuser_options_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='superhero_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
