# Generated by Django 5.1.7 on 2025-03-15 09:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_remove_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="superhero_name",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
