### User Signup
POST http://127.0.0.1:8000/signup/
Content-Type: application/json

{
  "email": "tarinisivakumar01022006@gmail.com",
  "password": "Test@1234",
  "gender": "male",
  "preference": "female"
}

### Verify OTP
POST http://127.0.0.1:8000/verify-otp/
Content-Type: application/json

{
  "email": "tarinisivakumar01022006@gmail.com",
  "otp": "183014"
}

### User Login
POST http://127.0.0.1:8000/login/
Content-Type: application/json

{
  "email": "tarinisivakumar01022006@gmail.com",
  "password": "Test@1234"
}

### Test Token Authentication
GET http://127.0.0.1:8000/test-token/
Authorization: Token b25704c40b0ea7bfc4e7c2a48cede26bb6b8b3d3

### Delete User
DELETE http://127.0.0.1:8000/delete-user/
Authorization: Token 83bc913f8f81166a2e213a6331e83b90d0171c94
